// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/approval.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApprovalEngineConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalEngineConfig) Reset() {
	*x = ApprovalEngineConfig{}
	mi := &file_internal_contracts_approval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalEngineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalEngineConfig) ProtoMessage() {}

func (x *ApprovalEngineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalEngineConfig.ProtoReflect.Descriptor instead.
func (*ApprovalEngineConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{0}
}

type ApprovalCreateConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId        string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Approvers         []string               `protobuf:"bytes,5,rep,name=approvers,proto3" json:"approvers,omitempty"`
	RequiredApprovals int32                  `protobuf:"varint,6,opt,name=required_approvals,json=requiredApprovals,proto3" json:"required_approvals,omitempty"`
	TtlSeconds        int32                  `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Engine            string                 `protobuf:"bytes,100,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApprovalCreateConfig) Reset() {
	*x = ApprovalCreateConfig{}
	mi := &file_internal_contracts_approval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalCreateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalCreateConfig) ProtoMessage() {}

func (x *ApprovalCreateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalCreateConfig.ProtoReflect.Descriptor instead.
func (*ApprovalCreateConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalCreateConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalCreateConfig) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ApprovalCreateConfig) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ApprovalCreateConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApprovalCreateConfig) GetApprovers() []string {
	if x != nil {
		return x.Approvers
	}
	return nil
}

func (x *ApprovalCreateConfig) GetRequiredApprovals() int32 {
	if x != nil {
		return x.RequiredApprovals
	}
	return 0
}

func (x *ApprovalCreateConfig) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *ApprovalCreateConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type ApprovalCreateArgs struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId        string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Approvers         []string               `protobuf:"bytes,5,rep,name=approvers,proto3" json:"approvers,omitempty"`
	RequiredApprovals int32                  `protobuf:"varint,6,opt,name=required_approvals,json=requiredApprovals,proto3" json:"required_approvals,omitempty"`
	TtlSeconds        int32                  `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApprovalCreateArgs) Reset() {
	*x = ApprovalCreateArgs{}
	mi := &file_internal_contracts_approval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalCreateArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalCreateArgs) ProtoMessage() {}

func (x *ApprovalCreateArgs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalCreateArgs.ProtoReflect.Descriptor instead.
func (*ApprovalCreateArgs) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{2}
}

func (x *ApprovalCreateArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalCreateArgs) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ApprovalCreateArgs) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ApprovalCreateArgs) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApprovalCreateArgs) GetApprovers() []string {
	if x != nil {
		return x.Approvers
	}
	return nil
}

func (x *ApprovalCreateArgs) GetRequiredApprovals() int32 {
	if x != nil {
		return x.RequiredApprovals
	}
	return 0
}

func (x *ApprovalCreateArgs) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ApprovalGetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Engine        string                 `protobuf:"bytes,100,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalGetConfig) Reset() {
	*x = ApprovalGetConfig{}
	mi := &file_internal_contracts_approval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalGetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalGetConfig) ProtoMessage() {}

func (x *ApprovalGetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalGetConfig.ProtoReflect.Descriptor instead.
func (*ApprovalGetConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{3}
}

func (x *ApprovalGetConfig) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalGetConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type ApprovalGetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalGetArgs) Reset() {
	*x = ApprovalGetArgs{}
	mi := &file_internal_contracts_approval_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalGetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalGetArgs) ProtoMessage() {}

func (x *ApprovalGetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalGetArgs.ProtoReflect.Descriptor instead.
func (*ApprovalGetArgs) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{4}
}

func (x *ApprovalGetArgs) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApprovalDecideConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Engine        string                 `protobuf:"bytes,100,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecideConfig) Reset() {
	*x = ApprovalDecideConfig{}
	mi := &file_internal_contracts_approval_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecideConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecideConfig) ProtoMessage() {}

func (x *ApprovalDecideConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecideConfig.ProtoReflect.Descriptor instead.
func (*ApprovalDecideConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{5}
}

func (x *ApprovalDecideConfig) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalDecideConfig) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ApprovalDecideConfig) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ApprovalDecideConfig) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ApprovalDecideConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type ApprovalDecideArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecideArgs) Reset() {
	*x = ApprovalDecideArgs{}
	mi := &file_internal_contracts_approval_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecideArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecideArgs) ProtoMessage() {}

func (x *ApprovalDecideArgs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecideArgs.ProtoReflect.Descriptor instead.
func (*ApprovalDecideArgs) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{6}
}

func (x *ApprovalDecideArgs) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalDecideArgs) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ApprovalDecideArgs) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ApprovalDecideArgs) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ApprovalListConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approver      string                 `protobuf:"bytes,1,opt,name=approver,proto3" json:"approver,omitempty"`
	Engine        string                 `protobuf:"bytes,100,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalListConfig) Reset() {
	*x = ApprovalListConfig{}
	mi := &file_internal_contracts_approval_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalListConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalListConfig) ProtoMessage() {}

func (x *ApprovalListConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalListConfig.ProtoReflect.Descriptor instead.
func (*ApprovalListConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{7}
}

func (x *ApprovalListConfig) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *ApprovalListConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type ApprovalListArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approver      string                 `protobuf:"bytes,1,opt,name=approver,proto3" json:"approver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalListArgs) Reset() {
	*x = ApprovalListArgs{}
	mi := &file_internal_contracts_approval_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalListArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalListArgs) ProtoMessage() {}

func (x *ApprovalListArgs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalListArgs.ProtoReflect.Descriptor instead.
func (*ApprovalListArgs) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{8}
}

func (x *ApprovalListArgs) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

type ApprovalEscalateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NewApprovers  []string               `protobuf:"bytes,2,rep,name=new_approvers,json=newApprovers,proto3" json:"new_approvers,omitempty"`
	Engine        string                 `protobuf:"bytes,100,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalEscalateConfig) Reset() {
	*x = ApprovalEscalateConfig{}
	mi := &file_internal_contracts_approval_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalEscalateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalEscalateConfig) ProtoMessage() {}

func (x *ApprovalEscalateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalEscalateConfig.ProtoReflect.Descriptor instead.
func (*ApprovalEscalateConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{9}
}

func (x *ApprovalEscalateConfig) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalEscalateConfig) GetNewApprovers() []string {
	if x != nil {
		return x.NewApprovers
	}
	return nil
}

func (x *ApprovalEscalateConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type ApprovalEscalateArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NewApprovers  []string               `protobuf:"bytes,2,rep,name=new_approvers,json=newApprovers,proto3" json:"new_approvers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalEscalateArgs) Reset() {
	*x = ApprovalEscalateArgs{}
	mi := &file_internal_contracts_approval_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalEscalateArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalEscalateArgs) ProtoMessage() {}

func (x *ApprovalEscalateArgs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalEscalateArgs.ProtoReflect.Descriptor instead.
func (*ApprovalEscalateArgs) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{10}
}

func (x *ApprovalEscalateArgs) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalEscalateArgs) GetNewApprovers() []string {
	if x != nil {
		return x.NewApprovers
	}
	return nil
}

type ApprovalWaitConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PollIntervalMs int32                  `protobuf:"varint,2,opt,name=poll_interval_ms,json=pollIntervalMs,proto3" json:"poll_interval_ms,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Engine         string                 `protobuf:"bytes,100,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApprovalWaitConfig) Reset() {
	*x = ApprovalWaitConfig{}
	mi := &file_internal_contracts_approval_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalWaitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalWaitConfig) ProtoMessage() {}

func (x *ApprovalWaitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalWaitConfig.ProtoReflect.Descriptor instead.
func (*ApprovalWaitConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{11}
}

func (x *ApprovalWaitConfig) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalWaitConfig) GetPollIntervalMs() int32 {
	if x != nil {
		return x.PollIntervalMs
	}
	return 0
}

func (x *ApprovalWaitConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ApprovalWaitConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type ApprovalWaitArgs struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PollIntervalMs int32                  `protobuf:"varint,2,opt,name=poll_interval_ms,json=pollIntervalMs,proto3" json:"poll_interval_ms,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApprovalWaitArgs) Reset() {
	*x = ApprovalWaitArgs{}
	mi := &file_internal_contracts_approval_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalWaitArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalWaitArgs) ProtoMessage() {}

func (x *ApprovalWaitArgs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalWaitArgs.ProtoReflect.Descriptor instead.
func (*ApprovalWaitArgs) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{12}
}

func (x *ApprovalWaitArgs) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalWaitArgs) GetPollIntervalMs() int32 {
	if x != nil {
		return x.PollIntervalMs
	}
	return 0
}

func (x *ApprovalWaitArgs) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ApprovalCheckExpiryArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalCheckExpiryArgs) Reset() {
	*x = ApprovalCheckExpiryArgs{}
	mi := &file_internal_contracts_approval_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalCheckExpiryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalCheckExpiryArgs) ProtoMessage() {}

func (x *ApprovalCheckExpiryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalCheckExpiryArgs.ProtoReflect.Descriptor instead.
func (*ApprovalCheckExpiryArgs) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{13}
}

type ApprovalDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         string                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecision) Reset() {
	*x = ApprovalDecision{}
	mi := &file_internal_contracts_approval_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecision) ProtoMessage() {}

func (x *ApprovalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecision.ProtoReflect.Descriptor instead.
func (*ApprovalDecision) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{14}
}

func (x *ApprovalDecision) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ApprovalDecision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ApprovalDecision) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ApprovalDecision) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ApprovalRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId        string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Approvers         []string               `protobuf:"bytes,5,rep,name=approvers,proto3" json:"approvers,omitempty"`
	RequiredApprovals int32                  `protobuf:"varint,6,opt,name=required_approvals,json=requiredApprovals,proto3" json:"required_approvals,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Decisions         []*ApprovalDecision    `protobuf:"bytes,8,rep,name=decisions,proto3" json:"decisions,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,9,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt         string                 `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Error             string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	TimedOut          bool                   `protobuf:"varint,101,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_internal_contracts_approval_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{15}
}

func (x *ApprovalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ApprovalRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ApprovalRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApprovalRequest) GetApprovers() []string {
	if x != nil {
		return x.Approvers
	}
	return nil
}

func (x *ApprovalRequest) GetRequiredApprovals() int32 {
	if x != nil {
		return x.RequiredApprovals
	}
	return 0
}

func (x *ApprovalRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApprovalRequest) GetDecisions() []*ApprovalDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *ApprovalRequest) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

func (x *ApprovalRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ApprovalRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *ApprovalRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApprovalRequest) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

type ApprovalListOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ApprovalRequest     `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalListOutput) Reset() {
	*x = ApprovalListOutput{}
	mi := &file_internal_contracts_approval_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalListOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalListOutput) ProtoMessage() {}

func (x *ApprovalListOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalListOutput.ProtoReflect.Descriptor instead.
func (*ApprovalListOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{16}
}

func (x *ApprovalListOutput) GetRequests() []*ApprovalRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ApprovalListOutput) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ApprovalListOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ApprovalCheckExpiryOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expired       []string               `protobuf:"bytes,1,rep,name=expired,proto3" json:"expired,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalCheckExpiryOutput) Reset() {
	*x = ApprovalCheckExpiryOutput{}
	mi := &file_internal_contracts_approval_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalCheckExpiryOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalCheckExpiryOutput) ProtoMessage() {}

func (x *ApprovalCheckExpiryOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_approval_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalCheckExpiryOutput.ProtoReflect.Descriptor instead.
func (*ApprovalCheckExpiryOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_approval_proto_rawDescGZIP(), []int{17}
}

func (x *ApprovalCheckExpiryOutput) GetExpired() []string {
	if x != nil {
		return x.Expired
	}
	return nil
}

func (x *ApprovalCheckExpiryOutput) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ApprovalCheckExpiryOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_approval_proto protoreflect.FileDescriptor

const file_internal_contracts_approval_proto_rawDesc = "" +
	"\n" +
	"!internal/contracts/approval.proto\x12\x1cworkflow.plugins.approval.v1\"\x16\n" +
	"\x14ApprovalEngineConfig\"\x85\x02\n" +
	"\x14ApprovalCreateConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tapprovers\x18\x05 \x03(\tR\tapprovers\x12-\n" +
	"\x12required_approvals\x18\x06 \x01(\x05R\x11requiredApprovals\x12\x1f\n" +
	"\vttl_seconds\x18\a \x01(\x05R\n" +
	"ttlSeconds\x12\x16\n" +
	"\x06engine\x18d \x01(\tR\x06engine\"\xeb\x01\n" +
	"\x12ApprovalCreateArgs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tapprovers\x18\x05 \x03(\tR\tapprovers\x12-\n" +
	"\x12required_approvals\x18\x06 \x01(\x05R\x11requiredApprovals\x12\x1f\n" +
	"\vttl_seconds\x18\a \x01(\x05R\n" +
	"ttlSeconds\"J\n" +
	"\x11ApprovalGetConfig\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06engine\x18d \x01(\tR\x06engine\"0\n" +
	"\x0fApprovalGetArgs\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x99\x01\n" +
	"\x14ApprovalDecideConfig\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x16\n" +
	"\x06engine\x18d \x01(\tR\x06engine\"\x7f\n" +
	"\x12ApprovalDecideArgs\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"H\n" +
	"\x12ApprovalListConfig\x12\x1a\n" +
	"\bapprover\x18\x01 \x01(\tR\bapprover\x12\x16\n" +
	"\x06engine\x18d \x01(\tR\x06engine\".\n" +
	"\x10ApprovalListArgs\x12\x1a\n" +
	"\bapprover\x18\x01 \x01(\tR\bapprover\"t\n" +
	"\x16ApprovalEscalateConfig\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rnew_approvers\x18\x02 \x03(\tR\fnewApprovers\x12\x16\n" +
	"\x06engine\x18d \x01(\tR\x06engine\"Z\n" +
	"\x14ApprovalEscalateArgs\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rnew_approvers\x18\x02 \x03(\tR\fnewApprovers\"\x9e\x01\n" +
	"\x12ApprovalWaitConfig\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12(\n" +
	"\x10poll_interval_ms\x18\x02 \x01(\x05R\x0epollIntervalMs\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12\x16\n" +
	"\x06engine\x18d \x01(\tR\x06engine\"\x84\x01\n" +
	"\x10ApprovalWaitArgs\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12(\n" +
	"\x10poll_interval_ms\x18\x02 \x01(\x05R\x0epollIntervalMs\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\x19\n" +
	"\x17ApprovalCheckExpiryArgs\"|\n" +
	"\x10ApprovalDecision\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xcd\x03\n" +
	"\x0fApprovalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tapprovers\x18\x05 \x03(\tR\tapprovers\x12-\n" +
	"\x12required_approvals\x18\x06 \x01(\x05R\x11requiredApprovals\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12L\n" +
	"\tdecisions\x18\b \x03(\v2..workflow.plugins.approval.v1.ApprovalDecisionR\tdecisions\x12-\n" +
	"\x12continuation_token\x18\t \x01(\tR\x11continuationToken\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\v \x01(\tR\texpiresAt\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\x12\x1b\n" +
	"\ttimed_out\x18e \x01(\bR\btimedOut\"\x8b\x01\n" +
	"\x12ApprovalListOutput\x12I\n" +
	"\brequests\x18\x01 \x03(\v2-.workflow.plugins.approval.v1.ApprovalRequestR\brequests\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"a\n" +
	"\x19ApprovalCheckExpiryOutput\x12\x18\n" +
	"\aexpired\x18\x01 \x03(\tR\aexpired\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBDZBgithub.com/GoCodeAlone/workflow-plugin-approval/internal/contractsb\x06proto3"

var (
	file_internal_contracts_approval_proto_rawDescOnce sync.Once
	file_internal_contracts_approval_proto_rawDescData []byte
)

func file_internal_contracts_approval_proto_rawDescGZIP() []byte {
	file_internal_contracts_approval_proto_rawDescOnce.Do(func() {
		file_internal_contracts_approval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_approval_proto_rawDesc), len(file_internal_contracts_approval_proto_rawDesc)))
	})
	return file_internal_contracts_approval_proto_rawDescData
}

var file_internal_contracts_approval_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_contracts_approval_proto_goTypes = []any{
	(*ApprovalEngineConfig)(nil),      // 0: workflow.plugins.approval.v1.ApprovalEngineConfig
	(*ApprovalCreateConfig)(nil),      // 1: workflow.plugins.approval.v1.ApprovalCreateConfig
	(*ApprovalCreateArgs)(nil),        // 2: workflow.plugins.approval.v1.ApprovalCreateArgs
	(*ApprovalGetConfig)(nil),         // 3: workflow.plugins.approval.v1.ApprovalGetConfig
	(*ApprovalGetArgs)(nil),           // 4: workflow.plugins.approval.v1.ApprovalGetArgs
	(*ApprovalDecideConfig)(nil),      // 5: workflow.plugins.approval.v1.ApprovalDecideConfig
	(*ApprovalDecideArgs)(nil),        // 6: workflow.plugins.approval.v1.ApprovalDecideArgs
	(*ApprovalListConfig)(nil),        // 7: workflow.plugins.approval.v1.ApprovalListConfig
	(*ApprovalListArgs)(nil),          // 8: workflow.plugins.approval.v1.ApprovalListArgs
	(*ApprovalEscalateConfig)(nil),    // 9: workflow.plugins.approval.v1.ApprovalEscalateConfig
	(*ApprovalEscalateArgs)(nil),      // 10: workflow.plugins.approval.v1.ApprovalEscalateArgs
	(*ApprovalWaitConfig)(nil),        // 11: workflow.plugins.approval.v1.ApprovalWaitConfig
	(*ApprovalWaitArgs)(nil),          // 12: workflow.plugins.approval.v1.ApprovalWaitArgs
	(*ApprovalCheckExpiryArgs)(nil),   // 13: workflow.plugins.approval.v1.ApprovalCheckExpiryArgs
	(*ApprovalDecision)(nil),          // 14: workflow.plugins.approval.v1.ApprovalDecision
	(*ApprovalRequest)(nil),           // 15: workflow.plugins.approval.v1.ApprovalRequest
	(*ApprovalListOutput)(nil),        // 16: workflow.plugins.approval.v1.ApprovalListOutput
	(*ApprovalCheckExpiryOutput)(nil), // 17: workflow.plugins.approval.v1.ApprovalCheckExpiryOutput
}
var file_internal_contracts_approval_proto_depIdxs = []int32{
	14, // 0: workflow.plugins.approval.v1.ApprovalRequest.decisions:type_name -> workflow.plugins.approval.v1.ApprovalDecision
	15, // 1: workflow.plugins.approval.v1.ApprovalListOutput.requests:type_name -> workflow.plugins.approval.v1.ApprovalRequest
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_contracts_approval_proto_init() }
func file_internal_contracts_approval_proto_init() {
	if File_internal_contracts_approval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_approval_proto_rawDesc), len(file_internal_contracts_approval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_approval_proto_goTypes,
		DependencyIndexes: file_internal_contracts_approval_proto_depIdxs,
		MessageInfos:      file_internal_contracts_approval_proto_msgTypes,
	}.Build()
	File_internal_contracts_approval_proto = out.File
	file_internal_contracts_approval_proto_goTypes = nil
	file_internal_contracts_approval_proto_depIdxs = nil
}
